name: node yml 
on:
  workflow_dispatch:
    
jobs:
  veracode:
    runs-on: ubuntu-latest
    steps:
    - actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: npm ci