on:
  push:
    branches:
      - main # ou la branche que vous utilisez pour le déploiement (par exemple, master)
  workflow_dispatch: # Permet de déclencher le workflow manuellement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Nécessaire pour publier sur GitHub Pages
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Nouvelle étape pour télécharger et extraire la soundbase
      - name: Download and extract soundbase
        run: |
          wget https://static.jean-cloud.net/oma-soundbases/soundbase_dev_latest.zip
          # Crée le dossier 'soundbase' et y extrait le contenu
          unzip soundbase_dev_latest.zip -d soundbase
          mkdir -p soundbase/website # Crée le répertoire 'website' à l'intérieur de 'soundbase'

      - name: Debug List templates directory content
        run: |
          echo "Contents of templates/ directory:"
          ls -R templates/
          echo "---"

      - name: Debug Check for episodes_serie.html content
        run: |
          if [ -f templates/episodes_serie.html ]; then
            echo "templates/episodes_serie.html exists. Its content:"
            cat templates/episodes_serie.html
          else
            echo "ERROR: templates/episodes_serie.html DOES NOT EXIST!"
          fi
          echo "---"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build Rust project
        # Commande corrigée sur une seule ligne
        run: cargo run --release -- --soundbase-path ./soundbase --radio-host 'https://myradio.example.com' --output public --website-prefix /website_test --player-url /website_test/player
    
      - name: List public directory content
        run: ls -R public # Ajouté pour le débogage
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
